FROM node:16.13.0-alpine3.14

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG NUXT_ENV_PUBLIC_URL
ARG APP_ENVIRONMENT
ARG SENTRY_DSN
ARG SENTRY_ENABLED
ARG SENTRY_SAMPLE_RATE
ARG NEW_RELIC_ACCOUNT_ID
ARG NEW_RELIC_APPLICATION_ID
ARG NEW_RELIC_LICENSE_KEY
ENV NUXT_ENV_PUBLIC_URL $NUXT_ENV_PUBLIC_URL
ENV APP_ENVIRONMENT $APP_ENVIRONMENT
ENV SENTRY_ENABLED $SENTRY_ENABLED
ENV SENTRY_DSN $SENTRY_DSN
ENV SENTRY_SAMPLE_RATE $SENTRY_SAMPLE_RATE
ENV NEW_RELIC_ACCOUNT_ID $NEW_RELIC_ACCOUNT_ID
ENV NEW_RELIC_APPLICATION_ID $NEW_RELIC_APPLICATION_ID
ENV NEW_RELIC_LICENSE_KEY $NEW_RELIC_LICENSE_KEY
ENV HOST 0.0.0.0
ENV PORT 3000

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
